pipeline {
    agent {
        docker {
            image 'python:3.11-slim'
        }
    }
    
    environment {
        FILE_LOCATION = 'example-voting-app/vote/' 
    }

    stages {
        stage('Get Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "pip install --no-cache-dir --upgrade --root=/tmp/pip-tmp -r ${FILE_LOCATION}requirements.txt"
            }
        }

        stage('Run App') {
            steps {
                sh 'python app.py'
            }
        }
    }
}

