pipeline{
    agent any
  
  stages{
    stage('getCode'){
      steps{
        checkout scm  
      }
    }

    stage('installDependencies'){
      steps{
        sh 'pip install -r requirements.txt' 
       }
    }

    stage('runApp'){
      steps{
          sh 'echo runApp'
        }
    }
    
    
  }
}
