pipeline{
  agent any
  
  environment {
        FILE_LOCATION = 'example-voting-app/' 
    }


  stages{
     
    stage('deployImage'){
    steps{
      withCredentials([sshUserPrivateKey(credentialsId: 'ec2', keyFileVariable: 'SSH_KEY', usernameVariable: 'Username')]){
      
        sh ''' 

            ssh -i \$SSH_KEY -o StrictHostKeyChecking=no \$Username@ec2-54-89-241-89.compute-1.amazonaws.com
            echo "Connected to EC2"
            docker ps
            docker stop vote || true
            docker rm vote || true
            docker compose up -d 
            docker ps
            
        '''
      }
    }
  }

    
    
  }
}
