pipeline {
  agent any

  environment {
    FILE_LOCATION = 'example-voting-app/' 
  }

  stages {
    stage('deployImage') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'ec2', keyFileVariable: 'SSH_KEY', usernameVariable: 'Username')]) {
          sh '''
            cd $FILE_LOCATION
            ssh -i $SSH_KEY -o StrictHostKeyChecking=no $Username@ec2-54-89-241-89.compute-1.amazonaws.com << 'EOF'
              echo "Connected to EC2"
              cd ~/example-voting-app  # adjust if needed
              docker ps
              docker compose up -d --build
              docker ps
            EOF
          '''
        }
      }
    }
  }
}

